version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - /opt/adv-map/prometheus/:/etc/prometheus/
      - /opt/adv-map/prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    networks:
      - meshtastic_map

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    environment:
      # increases the log level from info to debug
      - GF_LOG_LEVEL=debug
    ports:
      - '3000:3000'
    volumes:
      - '/opt/adv-map/grafana_storage:/var/lib/grafana'
    networks:
      - meshtastic_map

  meshtastic_exporter:
    build:
      context: .
    image: meshtastic_exporter
    container_name: meshtastic_exporter
    restart: unless-stopped
    environment:
      - HOST=meshtasticiphere
      # increases the log level from none to debug
#      - VERBOSE=1
    ports:
      - '8069:8096'
    networks:
      - meshtastic_map

networks:
  meshtastic_map:
