{
 "title": "Meshtastic PI",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Map",
   "type": "geomap",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "meshtastic_node_geohash{instance=\"meshtastic_exporter:8069\"}"
    }
   ]
  },
  {
   "title": "Node(s) Channel Utilization ",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "meshtastic_node_channel_util{instance=\"meshtastic_exporter:8069\"}",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Battery Levels",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "meshtastic_node_battery{instance=\"meshtastic_exporter:8069\"}",
     "legendFormat": "{{user}}"
    }
   ]
  }
 ]
}